-- =========================================================
-- VO IMPORT - COMPRAS DE INSUMOS
-- Ejecutar una sola vez en Supabase > SQL Editor
-- =========================================================

create table if not exists public.compras_insumos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    fecha_insumo timestamptz not null default now(),
    categoria text not null,
    concepto text not null,
    monto numeric(14,2) not null check (monto > 0),
    metodo_pago text,
    observaciones text,
    anulado boolean not null default false,
    anulado_at timestamptz
);

create index if not exists compras_insumos_fecha_idx
    on public.compras_insumos (fecha_insumo desc);

create index if not exists compras_insumos_anulado_idx
    on public.compras_insumos (anulado);

alter table public.compras_insumos enable row level security;

drop policy if exists "compras_insumos_select_authenticated"
    on public.compras_insumos;

create policy "compras_insumos_select_authenticated"
    on public.compras_insumos
    for select
    to authenticated
    using (true);

revoke all on table public.compras_insumos from anon;
grant select on table public.compras_insumos to authenticated;

-- ---------------------------------------------------------
-- REGISTRAR
-- ---------------------------------------------------------
create or replace function public.registrar_insumo(
    p_fecha_insumo timestamptz,
    p_categoria text,
    p_concepto text,
    p_monto numeric,
    p_metodo_pago text default null,
    p_observaciones text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id bigint;
begin
    if auth.uid() is null then
        raise exception 'No autorizado';
    end if;

    if p_fecha_insumo is null then
        raise exception 'La fecha es obligatoria';
    end if;

    if nullif(trim(p_categoria), '') is null then
        raise exception 'La categoría es obligatoria';
    end if;

    if nullif(trim(p_concepto), '') is null then
        raise exception 'El concepto es obligatorio';
    end if;

    if coalesce(p_monto, 0) <= 0 then
        raise exception 'El monto debe ser mayor a cero';
    end if;

    insert into public.compras_insumos (
        fecha_insumo,
        categoria,
        concepto,
        monto,
        metodo_pago,
        observaciones
    )
    values (
        p_fecha_insumo,
        trim(p_categoria),
        trim(p_concepto),
        p_monto,
        nullif(trim(coalesce(p_metodo_pago, '')), ''),
        nullif(trim(coalesce(p_observaciones, '')), '')
    )
    returning id into v_id;

    return v_id;
end;
$$;

-- ---------------------------------------------------------
-- EDITAR
-- ---------------------------------------------------------
create or replace function public.editar_insumo(
    p_insumo_id bigint,
    p_fecha_insumo timestamptz,
    p_categoria text,
    p_concepto text,
    p_monto numeric,
    p_metodo_pago text default null,
    p_observaciones text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null then
        raise exception 'No autorizado';
    end if;

    if p_insumo_id is null then
        raise exception 'Falta el ID de la compra';
    end if;

    if p_fecha_insumo is null then
        raise exception 'La fecha es obligatoria';
    end if;

    if nullif(trim(p_categoria), '') is null then
        raise exception 'La categoría es obligatoria';
    end if;

    if nullif(trim(p_concepto), '') is null then
        raise exception 'El concepto es obligatorio';
    end if;

    if coalesce(p_monto, 0) <= 0 then
        raise exception 'El monto debe ser mayor a cero';
    end if;

    update public.compras_insumos
    set
        fecha_insumo = p_fecha_insumo,
        categoria = trim(p_categoria),
        concepto = trim(p_concepto),
        monto = p_monto,
        metodo_pago = nullif(trim(coalesce(p_metodo_pago, '')), ''),
        observaciones = nullif(trim(coalesce(p_observaciones, '')), ''),
        updated_at = now()
    where id = p_insumo_id
      and anulado = false;

    if not found then
        raise exception 'La compra no existe o está anulada';
    end if;

    return p_insumo_id;
end;
$$;

-- ---------------------------------------------------------
-- ANULAR
-- ---------------------------------------------------------
create or replace function public.anular_insumo(
    p_insumo_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null then
        raise exception 'No autorizado';
    end if;

    if p_insumo_id is null then
        raise exception 'Falta el ID de la compra';
    end if;

    update public.compras_insumos
    set
        anulado = true,
        anulado_at = now(),
        updated_at = now()
    where id = p_insumo_id
      and anulado = false;

    if not found then
        raise exception 'La compra no existe o ya está anulada';
    end if;

    return p_insumo_id;
end;
$$;

revoke all on function public.registrar_insumo(timestamptz, text, text, numeric, text, text) from public;
revoke all on function public.editar_insumo(bigint, timestamptz, text, text, numeric, text, text) from public;
revoke all on function public.anular_insumo(bigint) from public;

grant execute on function public.registrar_insumo(timestamptz, text, text, numeric, text, text) to authenticated;
grant execute on function public.editar_insumo(bigint, timestamptz, text, text, numeric, text, text) to authenticated;
grant execute on function public.anular_insumo(bigint) to authenticated;
